### ISSUE TITLE
[bounty] Rewrite copy for landing page

### ISSUE THREAD

**Issue by limbofeather** [zestymarket/landing#13]
@blakep-eth has been working on creating marketing personas for Zesty, in hopes to better understand how we should be communicating Zesty externally across all our social surfaces. Here's some of the recent participation in the Zesty Governance Discourse: https://gov.zesty.market/t/development-of-marketing-personas/16

This is a proposal for a $250 bounty for @blakep.eth#5710 to work with @Srile on implementing new copy for the Zesty landing page.

**Comment by raftclara** [comment]
Is it still open?

**Comment by limbofeather** [comment]
Hey @raftclara yes it's still open, this is the Figma that @blakep-eth created: 
https://www.figma.com/file/g4Rr42K9TkukcAJpVKLWVP/ZM---Landing-Page?node-id=0%3A1

**Comment by raftclara** [comment]
How should I deliver it. I will read your material and I think it will be done today already.

**Comment by limbofeather** [comment]
@raftclara Are you a web developer? Will you be able to implement the copy as well?

**Comment by raftclara** [comment]
Yes, I Will be able to implement it. Don't worry.

**Comment by limbofeather** [comment]
@raftclara Can you join our Discord? https://discord.gg/4Jc3XhM5mp
